[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "static"

[dev]
  command = "flask run"
  port = 8080
  targetPort = 8080
  publish = "static"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 